---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.k8s-operator.pyar.bz
  resources:
  - securitychecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.k8s-operator.pyar.bz
  resources:
  - securitychecks/finalizers
  verbs:
  - update
- apiGroups:
  - security.k8s-operator.pyar.bz
  resources:
  - securitychecks/status
  verbs:
  - get
  - patch
  - update
